//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMJFAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kayttajat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kayttajat()
        {
            this.Ravintolat = new HashSet<Ravintolat>();
        }
    
        public int kayttajaId { get; set; }
        public string nimimerkki { get; set; }
        public string salasana { get; set; }
        public Nullable<int> kayttajanViestit { get; set; }
        public byte[] kuva { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ravintolat> Ravintolat { get; set; }
    }
}
