//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMJFAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ravintolat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ravintolat()
        {
            this.RavintolaKommentit = new HashSet<RavintolaKommentit>();
            this.Ruoka = new HashSet<Ruoka>();
        }
    
        public int ravintolaId { get; set; }
        public string ravintolanNimi { get; set; }
        public int kayttajaId { get; set; }
        public string osoite { get; set; }
        public Nullable<System.TimeSpan> ravintolaAvaa { get; set; }
        public Nullable<System.TimeSpan> ravintolaSulkee { get; set; }
        public Nullable<int> ratingDarra { get; set; }
        public Nullable<int> ratingKanni { get; set; }
        public Nullable<int> myyjat { get; set; }
        public byte[] kuva { get; set; }
        public byte[] alkoholi { get; set; }
    
        public virtual Kayttajat Kayttajat { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RavintolaKommentit> RavintolaKommentit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ruoka> Ruoka { get; set; }
    }
}
