//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMJFAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RavintolaKommentit
    {
        public int ravKommenttiID { get; set; }
        public int ravintolaId { get; set; }
        public int kayttajaId { get; set; }
        public string kommentti { get; set; }
        public byte[] kuva { get; set; }
        public Nullable<int> kanniRate { get; set; }
        public Nullable<int> darraRate { get; set; }
    
        public virtual Ravintolat Ravintolat { get; set; }
    }
}
