//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMJFAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RMJFDBEntities : DbContext
    {
        public RMJFDBEntities()
            : base("name=RMJFDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Kayttajat> Kayttajat { get; set; }
        public virtual DbSet<RavintolaKommentit> RavintolaKommentit { get; set; }
        public virtual DbSet<Ravintolat> Ravintolat { get; set; }
        public virtual DbSet<Ruoka> Ruoka { get; set; }
        public virtual DbSet<RuokaKommentit> RuokaKommentit { get; set; }
    }
}
