//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMJFAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ruoka
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ruoka()
        {
            this.RuokaKommentit = new HashSet<RuokaKommentit>();
        }
    
        public int ruokaId { get; set; }
        public int ravintolaId { get; set; }
        public byte[] kuva { get; set; }
        public string nimi { get; set; }
        public Nullable<decimal> darraIndeksi { get; set; }
        public Nullable<decimal> kanniIndeksi { get; set; }
        public int kayttajaId { get; set; }
        public Nullable<decimal> hinta { get; set; }
    
        public virtual Ravintolat Ravintolat { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RuokaKommentit> RuokaKommentit { get; set; }
    }
}
